#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &

cd $OPENSHIFT_REPO_DIR
nohup java -jar dropwizard-template-application/target/d3soft.dropwizard.example-0.0.1-SNAPSHOT.jar server dropwizard-template-application/example.openshift.yml > ${OPENSHIFT_DIY_LOG_DIR}/example.log 2>&1 & 

echo ""
echo "==================="
echo "Trifon - START - OK"
echo "==================="
echo ""